//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 02:36:08 PM EDT 
//


package com.intact.soa.rest.model.dp.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intact.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Policy_QNAME = new QName("", "Policy");
    private final static QName _InputSchemaURL_QNAME = new QName("", "InputSchemaURL");
    private final static QName _XForm_QNAME = new QName("", "XForm");
    private final static QName _URL_QNAME = new QName("", "URL");
    private final static QName _OutputSchemaURL_QNAME = new QName("", "OutputSchemaURL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intact.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BusinessServices }
     * 
     */
    public BusinessServices createBusinessServices() {
        return new BusinessServices();
    }

    /**
     * Create an instance of {@link SLA }
     * 
     */
    public SLA createSLA() {
        return new SLA();
    }

    /**
     * Create an instance of {@link SLD }
     * 
     */
    public SLD createSLD() {
        return new SLD();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link SLAs }
     * 
     */
    public SLAs createSLAs() {
        return new SLAs();
    }

    /**
     * Create an instance of {@link ServiceVersion }
     * 
     */
    public ServiceVersion createServiceVersion() {
        return new ServiceVersion();
    }

    /**
     * Create an instance of {@link EndPoint }
     * 
     */
    public EndPoint createEndPoint() {
        return new EndPoint();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Policy")
    public JAXBElement<String> createPolicy(String value) {
        return new JAXBElement<String>(_Policy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InputSchemaURL")
    public JAXBElement<String> createInputSchemaURL(String value) {
        return new JAXBElement<String>(_InputSchemaURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XForm")
    public JAXBElement<String> createXForm(String value) {
        return new JAXBElement<String>(_XForm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "URL")
    public JAXBElement<String> createURL(String value) {
        return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutputSchemaURL")
    public JAXBElement<String> createOutputSchemaURL(String value) {
        return new JAXBElement<String>(_OutputSchemaURL_QNAME, String.class, null, value);
    }

}
