//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 02:36:08 PM EDT 
//


package com.intact.soa.rest.model.dp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SLAs"/>
 *         &lt;element ref="{}SLD"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "slAs",
    "sld"
})
@XmlRootElement(name = "ServiceVersion")
public class ServiceVersion {

    @XmlElement(name = "SLAs", required = true)
    protected SLAs slAs;
    @XmlElement(name = "SLD", required = true)
    protected SLD sld;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String uri;

    /**
     * Gets the value of the slAs property.
     * 
     * @return
     *     possible object is
     *     {@link SLAs }
     *     
     */
    public SLAs getSLAs() {
        return slAs;
    }

    /**
     * Sets the value of the slAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SLAs }
     *     
     */
    public void setSLAs(SLAs value) {
        this.slAs = value;
    }

    /**
     * Gets the value of the sld property.
     * 
     * @return
     *     possible object is
     *     {@link SLD }
     *     
     */
    public SLD getSLD() {
        return sld;
    }

    /**
     * Sets the value of the sld property.
     * 
     * @param value
     *     allowed object is
     *     {@link SLD }
     *     
     */
    public void setSLD(SLD value) {
        this.sld = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

}
