//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 02:36:08 PM EDT 
//


package com.nostrasoft.da.rest.model.dp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}InputSchemaURL" minOccurs="0"/>
 *         &lt;element ref="{}XForm" minOccurs="0"/>
 *         &lt;element ref="{}OutputSchemaURL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputSchemaURL",
    "xForm",
    "outputSchemaURL"
})
@XmlRootElement(name = "Response")
public class Response {

    @XmlElement(name = "InputSchemaURL")
    protected String inputSchemaURL;
    @XmlElement(name = "XForm")
    protected String xForm;
    @XmlElement(name = "OutputSchemaURL")
    protected String outputSchemaURL;

    /**
     * Gets the value of the inputSchemaURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputSchemaURL() {
        return inputSchemaURL;
    }

    /**
     * Sets the value of the inputSchemaURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputSchemaURL(String value) {
        this.inputSchemaURL = value;
    }

    /**
     * Gets the value of the xForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXForm() {
        return xForm;
    }

    /**
     * Sets the value of the xForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXForm(String value) {
        this.xForm = value;
    }

    /**
     * Gets the value of the outputSchemaURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputSchemaURL() {
        return outputSchemaURL;
    }

    /**
     * Sets the value of the outputSchemaURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputSchemaURL(String value) {
        this.outputSchemaURL = value;
    }

}
